interface ReportData {
  id: string
  productName: string
  productId: string
  category: string
  complianceScore: number
  status: string
  date: string
  violations: Array<{
    type: string
    severity: string
    description: string
  }>
  factoryInfo: {
    factoryName: string
    city: string
    region: string
    manufacturingDate: string
    destination: string
  }
  lawViolations: Array<{
    law: string
    section: string
    description: string
  }>
}

export function generatePDFContent(data: ReportData): string {
  return `
LEGAL METROLOGY COMPLIANCE REPORT
=====================================
Report ID: ${data.id}
Generated: ${new Date().toLocaleDateString()}

PRODUCT INFORMATION
------------------
Product Name: ${data.productName}
Product ID: ${data.productId}
Category: ${data.category}
Compliance Score: ${data.complianceScore}%
Status: ${data.status}
Inspection Date: ${data.date}

FACTORY & LOCATION INFORMATION
-------------------------------
Factory Name: ${data.factoryInfo.factoryName}
City: ${data.factoryInfo.city}
Region: ${data.factoryInfo.region}
Manufacturing Date: ${data.factoryInfo.manufacturingDate}
Destination: ${data.factoryInfo.destination}

COMPLIANCE ANALYSIS
-------------------
${data.violations.length > 0 ? `Total Violations: ${data.violations.length}` : 'No violations detected'}

${data.violations.map((v, i) => `
${i + 1}. ${v.type}
   Severity: ${v.severity}
   Description: ${v.description}
`).join('')}

LAW VIOLATIONS
--------------
${data.lawViolations.length > 0 ? data.lawViolations.map((l, i) => `
${i + 1}. ${l.law}
   Section: ${l.section}
   Description: ${l.description}
`).join('') : 'No law violations detected'}

REPORT SUMMARY
--------------
This report was generated by the Legal Metrology Compliance Platform.
For official purposes, please contact the relevant authority.

Generated on: ${new Date().toLocaleString()}
=====================================
  `.trim()
}

export function downloadPDF(data: ReportData) {
  const content = generatePDFContent(data)
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `compliance-report-${data.id}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
